from enum import StrEnum

SUPPORTED_OPERATIONS = ("fit", "predict")
SUPPORTED_DEVICES = ("cpu", "cuda", "auto")


class JobState(StrEnum):
    UPLOADING = "UPLOADING"
    SEALED = "SEALED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"


TERMINAL_STATES = frozenset({
    JobState.SUCCEEDED,
    JobState.FAILED,
    JobState.CANCELLED,
})

IMMEDIATE_CANCEL_STATES = frozenset({
    JobState.UPLOADING,
    JobState.SEALED,
    JobState.QUEUED,
    JobState.RETRYING,
})

STATE_TRANSITIONS = {
    JobState.UPLOADING: frozenset({JobState.SEALED, JobState.CANCELLED}),
    JobState.SEALED: frozenset({JobState.QUEUED, JobState.CANCELLED}),
    JobState.QUEUED: frozenset({JobState.RUNNING, JobState.CANCELLED}),
    JobState.RUNNING: frozenset({
        JobState.SUCCEEDED,
        JobState.FAILED,
        JobState.CANCELLING,
        JobState.RETRYING,
    }),
    JobState.RETRYING: frozenset({
        JobState.RUNNING,
        JobState.FAILED,
        JobState.CANCELLED,
    }),
    JobState.CANCELLING: frozenset({JobState.CANCELLED}),
    JobState.SUCCEEDED: frozenset(),
    JobState.FAILED: frozenset(),
    JobState.CANCELLED: frozenset(),
}


class ErrorCode(StrEnum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    FAILED_PRECONDITION = "FAILED_PRECONDITION"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    CANCELLED = "CANCELLED"
    UNAVAILABLE = "UNAVAILABLE"
    INTERNAL = "INTERNAL"

    DEVICE_UNAVAILABLE = "DEVICE_UNAVAILABLE"
    DEVICE_LOST = "DEVICE_LOST"
    EXECUTION_INTERRUPTED = "EXECUTION_INTERRUPTED"
    SUBPROCESS_FAILED = "SUBPROCESS_FAILED"
    SUBPROCESS_HUNG = "SUBPROCESS_HUNG"
    WORKER_PROTOCOL_VIOLATION = "WORKER_PROTOCOL_VIOLATION"
    MALFORMED_OUTPUT = "MALFORMED_OUTPUT"
    CUDA_OUT_OF_MEMORY = "CUDA_OUT_OF_MEMORY"
    DISK_FULL = "DISK_FULL"
    RECOVERY_CHECKPOINT_UNAVAILABLE = "RECOVERY_CHECKPOINT_UNAVAILABLE"
    RECOVERY_CHECKPOINT_INCOMPATIBLE = "RECOVERY_CHECKPOINT_INCOMPATIBLE"
    RECOVERY_INPUT_UNAVAILABLE = "RECOVERY_INPUT_UNAVAILABLE"

