CONTRACT_NAME = "transformer-training-telemetry"
CONTRACT_REVISION = 1

REPORT_ACTION = "transformer.training-telemetry.v1.report"
GRADIENT_INTERACTIONS_ACTION = "transformer.training-telemetry.v1.gradient-interactions"

MAX_EPOCH_PAGE_SIZE = 100
MAX_GRADIENT_PAIR_PAGE_SIZE = 1_000
CURSOR_TTL_SECONDS = 900
MAX_RESPONSE_BYTES = 8 * 1024 * 1024
MAX_RETAINED_SNAPSHOT_COUNT = 64
MAX_RETAINED_SNAPSHOT_BYTES = 16 * 1024 * 1024
MAX_RETAINED_SNAPSHOT_TOTAL_BYTES = 64 * 1024 * 1024
SNAPSHOT_CAPACITY_RETRY_AFTER_SECONDS = 30

__all__ = [
    "CONTRACT_NAME",
    "CONTRACT_REVISION",
    "CURSOR_TTL_SECONDS",
    "GRADIENT_INTERACTIONS_ACTION",
    "MAX_EPOCH_PAGE_SIZE",
    "MAX_GRADIENT_PAIR_PAGE_SIZE",
    "MAX_RESPONSE_BYTES",
    "MAX_RETAINED_SNAPSHOT_BYTES",
    "MAX_RETAINED_SNAPSHOT_COUNT",
    "MAX_RETAINED_SNAPSHOT_TOTAL_BYTES",
    "REPORT_ACTION",
    "SNAPSHOT_CAPACITY_RETRY_AFTER_SECONDS",
]
