CONTRACT_NAME = "transformer-target-head-diagnostics"
CONTRACT_REVISION = 1

REPORT_ACTION = "transformer.target-head-diagnostics.v1.report"

MAX_EPOCH_PAGE_SIZE = 100
CURSOR_TTL_SECONDS = 900
MAX_RESPONSE_BYTES = 8 * 1024 * 1024
MAX_COMMITTED_ARTIFACT_ROWS = 2_000_000
MAX_RETAINED_SNAPSHOT_COUNT = 64
MAX_RETAINED_SNAPSHOT_BYTES = 16 * 1024 * 1024
MAX_RETAINED_SNAPSHOT_TOTAL_BYTES = 64 * 1024 * 1024
SNAPSHOT_CAPACITY_RETRY_AFTER_SECONDS = 30

ARTIFACT_FORMAT = "transformer-target-head-diagnostics-v1"

__all__ = [
    "ARTIFACT_FORMAT",
    "CONTRACT_NAME",
    "CONTRACT_REVISION",
    "CURSOR_TTL_SECONDS",
    "MAX_COMMITTED_ARTIFACT_ROWS",
    "MAX_EPOCH_PAGE_SIZE",
    "MAX_RESPONSE_BYTES",
    "MAX_RETAINED_SNAPSHOT_BYTES",
    "MAX_RETAINED_SNAPSHOT_COUNT",
    "MAX_RETAINED_SNAPSHOT_TOTAL_BYTES",
    "REPORT_ACTION",
    "SNAPSHOT_CAPACITY_RETRY_AFTER_SECONDS",
]
