import os

from app.contracts.worker.v2.config import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_CONTEXT_MODE,
    DEFAULT_DETERMINISTIC,
    DEFAULT_DROPOUT,
    DEFAULT_EPOCHS,
    DEFAULT_HIDDEN,
    DEFAULT_LAYERS,
    DEFAULT_LOSS_SCHEDULE,
    DEFAULT_LOSS_STAGE,
    DEFAULT_LR,
    DEFAULT_NHEAD,
    DEFAULT_PATIENCE,
    DEFAULT_SAVE_BEST_CHECKPOINT,
    DEFAULT_SEED,
    DEFAULT_STAGE_SIZE,
    DEFAULT_TRAIN_MONITOR,
    DEFAULT_TRAIN_MONITOR_MIN_IMPROVEMENT,
    DEFAULT_WEIGHT_DECAY,
)

PROJECT_NAME = "transformer"
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HOST_DEFAULT = "127.0.0.1"
PORT_DEFAULT = 8815
ALLOW_PLAINTEXT = True

CPU_WORKERS = 2
RETENTION_SECONDS = 7 * 24 * 60 * 60

D_MODEL = DEFAULT_HIDDEN
NHEAD = DEFAULT_NHEAD
NUM_LAYERS = DEFAULT_LAYERS
DROPOUT = DEFAULT_DROPOUT
CONTEXT_MODE = DEFAULT_CONTEXT_MODE

LR = DEFAULT_LR
BATCH_SIZE = DEFAULT_BATCH_SIZE
EPOCHS = DEFAULT_EPOCHS
PATIENCE = DEFAULT_PATIENCE
WEIGHT_DECAY = DEFAULT_WEIGHT_DECAY
GRAD_CLIP_NORM = 1.0
LOSS_STAGE = DEFAULT_LOSS_STAGE
LOSS_SCHEDULE = DEFAULT_LOSS_SCHEDULE
STAGE_SIZE = DEFAULT_STAGE_SIZE
TRAIN_MONITOR = DEFAULT_TRAIN_MONITOR
TRAIN_MONITOR_MIN_IMPROVEMENT = DEFAULT_TRAIN_MONITOR_MIN_IMPROVEMENT
SAVE_BEST_CHECKPOINT = DEFAULT_SAVE_BEST_CHECKPOINT
SEED = DEFAULT_SEED
DETERMINISTIC = DEFAULT_DETERMINISTIC

DEFAULT_DEVICE = "cpu"
DEFAULT_MAX_FRAME_BYTES = 512 * 1024 * 1024
