import os
import tempfile

from app.project import PROJECT_NAME

# Local runtime.
DEFAULT_DEVICE = "cpu"
DEFAULT_MAX_FRAME_BYTES = 512 * 1024 * 1024

# Flight service.
HOST_DEFAULT = "127.0.0.1"
PORT_DEFAULT = 8815
ALLOW_PLAINTEXT = True
CPU_WORKERS = 2
RETENTION_SECONDS = 7 * 24 * 60 * 60

RUNTIME_DIR_DEFAULT = os.path.join(tempfile.gettempdir(), PROJECT_NAME)
MAX_MESSAGE_BYTES_DEFAULT = 16 * 1024 * 1024
TARGET_BATCH_BYTES_DEFAULT = 8 * 1024 * 1024
MAX_BATCH_BYTES_DEFAULT = 16 * 1024 * 1024
MAX_PAYLOAD_BYTES_DEFAULT = 512 * 1024 * 1024
MAX_ROWS_PER_PAYLOAD_DEFAULT = 2_000_000
MAX_JOB_BYTES_DEFAULT = 64 * 1024 * 1024 * 1024
MAX_ACTIVE_JOBS_PER_SUBJECT_DEFAULT = 32
TICKET_TTL_SECONDS_DEFAULT = 600
CANCEL_GRACE_SECONDS_DEFAULT = 10.0
SHUTDOWN_DRAIN_SECONDS_DEFAULT = 30.0
MAINTENANCE_INTERVAL_SECONDS_DEFAULT = 60
SUBPROCESS_TIMEOUT_SECONDS_DEFAULT = 24 * 60 * 60
INPUT_IDLE_TIMEOUT_SECONDS_DEFAULT = 15 * 60
ACQUIRE_IDLE_GRACE_SECONDS_DEFAULT = 30.0

# PostgreSQL.
POSTGRES_PORT_DEFAULT = 5432
POSTGRES_SCHEMA_DEFAULT = "transformer"

# OpenSearch metrics.
OPENSEARCH_CONNECT_TIMEOUT_SECONDS_DEFAULT = 3.0
OPENSEARCH_REQUEST_TIMEOUT_SECONDS_DEFAULT = 15.0
OPENSEARCH_MAX_BULK_DOCUMENTS_DEFAULT = 500
OPENSEARCH_MAX_BULK_BYTES_DEFAULT = 2 * 1024 * 1024

__all__ = [
    "ACQUIRE_IDLE_GRACE_SECONDS_DEFAULT",
    "ALLOW_PLAINTEXT",
    "CANCEL_GRACE_SECONDS_DEFAULT",
    "CPU_WORKERS",
    "DEFAULT_DEVICE",
    "DEFAULT_MAX_FRAME_BYTES",
    "HOST_DEFAULT",
    "INPUT_IDLE_TIMEOUT_SECONDS_DEFAULT",
    "MAINTENANCE_INTERVAL_SECONDS_DEFAULT",
    "MAX_ACTIVE_JOBS_PER_SUBJECT_DEFAULT",
    "MAX_BATCH_BYTES_DEFAULT",
    "MAX_JOB_BYTES_DEFAULT",
    "MAX_MESSAGE_BYTES_DEFAULT",
    "MAX_PAYLOAD_BYTES_DEFAULT",
    "MAX_ROWS_PER_PAYLOAD_DEFAULT",
    "OPENSEARCH_CONNECT_TIMEOUT_SECONDS_DEFAULT",
    "OPENSEARCH_MAX_BULK_BYTES_DEFAULT",
    "OPENSEARCH_MAX_BULK_DOCUMENTS_DEFAULT",
    "OPENSEARCH_REQUEST_TIMEOUT_SECONDS_DEFAULT",
    "PORT_DEFAULT",
    "POSTGRES_PORT_DEFAULT",
    "POSTGRES_SCHEMA_DEFAULT",
    "RETENTION_SECONDS",
    "RUNTIME_DIR_DEFAULT",
    "SHUTDOWN_DRAIN_SECONDS_DEFAULT",
    "SUBPROCESS_TIMEOUT_SECONDS_DEFAULT",
    "TARGET_BATCH_BYTES_DEFAULT",
    "TICKET_TTL_SECONDS_DEFAULT",
]
