import argparse

from config import (
    DEFAULT_DEVICE,
    LR,
    BATCH_SIZE,
    EPOCHS,
    PER_WEEK,
    PATIENCE,
    D_MODEL,
    NUM_LAYERS,
    DROPOUT,
    NHEAD,
)
from version import version_text


APP_DESCRIPTION = """Transformer training and inference CLI.

Data contract:
  src              Arrow list<float>, flattened [seq_len * feature_dim].
  tgt              Arrow list<float>, required for fit and fit-stream.
  predictions      Arrow list<float>, written to --pred-col.

Modes:
  fit              Train from an Arrow file on disk.
  predict          Load a model and write predictions to an Arrow file.
  fit-stream       Train from framed Arrow payloads on stdin.
  predict-stream   Predict from framed Arrow payloads on stdin.
  plot-metrics     Render SVG charts from a metrics JSONL file in models/.

Streaming protocol:
  8-byte unsigned big-endian payload length, followed by an Arrow IPC file.
  predict-stream writes the same framed protocol to stdout.

Storage:
  Models and metrics JSONL files are resolved relative to models/.
"""

APP_EPILOG = """Examples:
  python ./app/main.py fit ./data/train.arrow --seq-len=20
  python ./app/main.py fit ./data/train.arrow --seq-len=20 --metrics-name=train.jsonl
  python ./app/main.py fit-stream --seq-len=20 --model-name=model.pth --metrics-name=train-stream.jsonl
  python ./app/main.py predict-stream --seq-len=20 --model-name=model.pth > preds.framed
  python ./app/main.py plot-metrics train.jsonl --plots-dir=metrics_plots
  python ./app/main.py --version
"""


def build_parser():
    parser = argparse.ArgumentParser(
        prog="main.py",
        description=APP_DESCRIPTION,
        epilog=APP_EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "action",
        choices=["fit", "predict", "fit-stream", "predict-stream", "plot-metrics"],
        help="Select the execution mode.",
    )

    parser.add_argument(
        "data",
        nargs="?",
        help="Input Arrow file for fit/predict, or metrics JSONL for plot-metrics.",
    )

    runtime = parser.add_argument_group("Runtime")
    model = parser.add_argument_group("Model")
    train = parser.add_argument_group("Training")

    runtime.add_argument("--device", choices=["cpu", "gpu"], default=DEFAULT_DEVICE,
                         help="Runtime device. gpu falls back to cpu when CUDA is unavailable.")
    runtime.add_argument("--model-name", default="model_weights.pth",
                         help="Model weights file name inside models/.")
    runtime.add_argument("--preds-path", default="/tmp/preds.arrow",
                         help="Arrow output path for predict mode.")
    runtime.add_argument("--pred-col", default="out",
                         help="Prediction column name.")
    runtime.add_argument("--metrics-name", default=None,
                         help="Metrics JSONL file name inside models/.")
    runtime.add_argument("--plots-dir", default="metrics_plots",
                         help="Directory for SVG charts generated by plot-metrics.")

    model.add_argument("--seq-len", type=int, default=None,
                       help="Sequence length. Required for all data modes.")
    model.add_argument("--hidden", type=int, default=D_MODEL,
                       help="Transformer hidden dimension.")
    model.add_argument("--layers", type=int, default=NUM_LAYERS,
                       help="Number of Transformer encoder layers.")
    model.add_argument("--dropout", type=float, default=DROPOUT,
                       help="Dropout probability.")
    model.add_argument("--nhead", type=int, default=NHEAD,
                       help="Number of attention heads.")

    train.add_argument("--lr", type=float, default=LR,
                       help="Learning rate.")
    train.add_argument("--batch-size", type=int, default=BATCH_SIZE,
                       help="Mini-batch size.")
    train.add_argument("--epochs", type=int, default=EPOCHS,
                       help="Epoch count for fit mode.")
    train.add_argument("--per-week", type=int, default=PER_WEEK,
                       help="Epoch/frame count per loss schedule week.")
    train.add_argument("--patience", type=int, default=PATIENCE,
                       help="Early stopping patience placeholder.")

    parser.add_argument(
        "--use-amp",
        action="store_true",
        help="Use mixed precision (AMP) if GPU available.",
    )

    parser.add_argument(
        "--version",
        action="version",
        version=version_text("%(prog)s"),
    )

    return parser
