OBJECTIVE_LANGUAGE_REVISION = 1

CONSTRAINTS = ("ClosedInterval", "Finite")
TRANSFORMATIONS = ("Identity", "Sigmoid", "Tanh")
RESOURCE_KINDS = ("PositiveScalarPerObservation",)
DIRECT_OPERATORS = (
    "BinaryCrossEntropyWithLogits",
    "LogMSE",
    "SmoothL1",
)
AUXILIARY_OPERATORS = (
    "ExpectedValue",
    "GaussianNLL",
    "RiskAdjustedExpectedValue",
)
AGGREGATIONS = ("WeightedSum",)
REDUCTIONS = ("GlobalRowMean",)

MODEL_ARCHITECTURE_IDENTITY = "transformer.sequence-model"
MODEL_ARCHITECTURE_REVISION = 1

MAX_TARGET_SLOTS = 128
MAX_OBJECTIVE_COMPONENTS = 256
MAX_PRIVATE_RESOURCES = 64

__all__ = [
    "AGGREGATIONS",
    "AUXILIARY_OPERATORS",
    "CONSTRAINTS",
    "DIRECT_OPERATORS",
    "MAX_OBJECTIVE_COMPONENTS",
    "MAX_PRIVATE_RESOURCES",
    "MAX_TARGET_SLOTS",
    "MODEL_ARCHITECTURE_IDENTITY",
    "MODEL_ARCHITECTURE_REVISION",
    "OBJECTIVE_LANGUAGE_REVISION",
    "REDUCTIONS",
    "RESOURCE_KINDS",
    "TRANSFORMATIONS",
]

