from app.contracts.model_catalog.v6.constants import (
    DETAIL_ACTION as MODEL_CATALOG_DETAIL_ACTION,
    LIST_ACTION as MODEL_CATALOG_LIST_ACTION,
)
from app.contracts.model_topology.v2.constants import (
    DETAIL_ACTION as MODEL_TOPOLOGY_DETAIL_ACTION,
)
from app.contracts.target_head_diagnostics.v4.constants import (
    REPORT_ACTION as TARGET_HEAD_DIAGNOSTICS_REPORT_ACTION,
)
from app.contracts.training_telemetry.v4.constants import (
    GRADIENT_INTERACTIONS_ACTION as TRAINING_TELEMETRY_GRADIENT_ACTION,
    REPORT_ACTION as TRAINING_TELEMETRY_REPORT_ACTION,
)
from app.contracts.worker.v19.constants import (
    FIT_INPUT_SCHEMA_ID,
    PREDICT_INPUT_SCHEMA_ID,
    PREDICTION_OUTPUT_SCHEMA_ID,
)

CONTRACT_NAME = "transformer-flight"
CONTRACT_VERSION = 21
CONTRACT_PATH_VERSION = "v21"

CAPABILITIES_ACTION = "transformer.v21.capabilities"
HEALTH_ACTION = "transformer.v21.health"
FIT_CREATE_ACTION = "transformer.v21.fit.create"
PREDICT_CREATE_ACTION = "transformer.v21.predict.create"
ACQUIRE_ACTION = "transformer.v21.job.acquire"
STATUS_ACTION = "transformer.v21.job.status"
INPUTS_LIST_ACTION = "transformer.v21.job.inputs.list"
INPUT_CLOSE_ACTION = "transformer.v21.job.input.close"
OUTPUTS_LIST_ACTION = "transformer.v21.job.outputs.list"
CANCEL_ACTION = "transformer.v21.job.cancel"

ACTIONS = (
    CAPABILITIES_ACTION,
    HEALTH_ACTION,
    FIT_CREATE_ACTION,
    PREDICT_CREATE_ACTION,
    ACQUIRE_ACTION,
    STATUS_ACTION,
    INPUTS_LIST_ACTION,
    INPUT_CLOSE_ACTION,
    OUTPUTS_LIST_ACTION,
    CANCEL_ACTION,
    MODEL_CATALOG_LIST_ACTION,
    MODEL_CATALOG_DETAIL_ACTION,
    MODEL_TOPOLOGY_DETAIL_ACTION,
    TRAINING_TELEMETRY_REPORT_ACTION,
    TRAINING_TELEMETRY_GRADIENT_ACTION,
    TARGET_HEAD_DIAGNOSTICS_REPORT_ACTION,
)

FIT_SCHEMA_ID = FIT_INPUT_SCHEMA_ID
PREDICT_SCHEMA_ID = PREDICT_INPUT_SCHEMA_ID
PREDICTION_SCHEMA_ID = PREDICTION_OUTPUT_SCHEMA_ID

MAX_PAYLOADS_PER_JOB = 100_000
MAX_PAGE_ITEMS = 100

__all__ = [
    "ACQUIRE_ACTION",
    "ACTIONS",
    "CANCEL_ACTION",
    "CAPABILITIES_ACTION",
    "CONTRACT_NAME",
    "CONTRACT_PATH_VERSION",
    "CONTRACT_VERSION",
    "FIT_CREATE_ACTION",
    "FIT_SCHEMA_ID",
    "HEALTH_ACTION",
    "INPUTS_LIST_ACTION",
    "INPUT_CLOSE_ACTION",
    "MAX_PAGE_ITEMS",
    "MAX_PAYLOADS_PER_JOB",
    "MODEL_CATALOG_DETAIL_ACTION",
    "MODEL_CATALOG_LIST_ACTION",
    "MODEL_TOPOLOGY_DETAIL_ACTION",
    "OUTPUTS_LIST_ACTION",
    "PREDICTION_SCHEMA_ID",
    "PREDICT_CREATE_ACTION",
    "PREDICT_SCHEMA_ID",
    "STATUS_ACTION",
    "TARGET_HEAD_DIAGNOSTICS_REPORT_ACTION",
    "TRAINING_TELEMETRY_GRADIENT_ACTION",
    "TRAINING_TELEMETRY_REPORT_ACTION",
]
